"""empty message

Revision ID: 2b37ebec28d4
Revises: c0835c810501
Create Date: 2021-08-10 22:01:27.611252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b37ebec28d4'
down_revision = 'c0835c810501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=6), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('drowsiness_data',
    sa.Column('d_data', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('d_time', sa.DateTime(), nullable=False),
    sa.Column('d_picture', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('d_data')
    )
    op.add_column('time_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'time_table', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_table', type_='foreignkey')
    op.drop_column('time_table', 'user_id')
    op.drop_table('drowsiness_data')
    op.drop_table('user')
    # ### end Alembic commands ###
