"""empty message

Revision ID: c0835c810501
Revises: 6c813ed3f9f7
Create Date: 2021-08-09 17:46:06.368972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0835c810501'
down_revision = '6c813ed3f9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monClass', sa.String(length=200), nullable=True),
    sa.Column('tuesClass', sa.String(length=200), nullable=True),
    sa.Column('wedClass', sa.String(length=200), nullable=True),
    sa.Column('thursClass', sa.String(length=200), nullable=True),
    sa.Column('friClass', sa.String(length=200), nullable=True),
    sa.Column('satClass', sa.String(length=200), nullable=True),
    sa.Column('sunClass', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('time_table')
    # ### end Alembic commands ###
