"""empty message

Revision ID: c9287de5b9e6
Revises: 
Create Date: 2021-08-16 20:47:05.614390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9287de5b9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('drowsiness_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('d_time', sa.DateTime(), nullable=False),
    sa.Column('d_picture', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('monClass', sa.String(length=200), nullable=True),
    sa.Column('tuesClass', sa.String(length=200), nullable=True),
    sa.Column('wedClass', sa.String(length=200), nullable=True),
    sa.Column('thursClass', sa.String(length=200), nullable=True),
    sa.Column('friClass', sa.String(length=200), nullable=True),
    sa.Column('satClass', sa.String(length=200), nullable=True),
    sa.Column('sunClass', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_table')
    op.drop_table('drowsiness_data')
    op.drop_table('user')
    # ### end Alembic commands ###
